// demos/style/react-component-node-style/src/App.tsx
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML.
 ** Copyright (c) by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import { DiagramComponent } from './DiagramComponent'
import { ReactComponentHtmlNodeStyle } from './ReactComponentHtmlNodeStyle'
import { HtmlNodeComponent } from './HtmlNodeComponent'
import graphData from './assets/graph-data.json'
import { GraphComponent, GraphEditorInputMode, Size } from '@yfiles/yfiles'

function initGraph(graphComponent: GraphComponent) {
  graphComponent.inputMode = new GraphEditorInputMode({ allowEditLabelOnDoubleClick: false })

  // create the style instance using our component, providing defaults for the tag
  const style = new ReactComponentHtmlNodeStyle(
    // the React component used to render a node
    HtmlNodeComponent,
    // the props the component should receive
    (_, node) => node.tag ?? { name: 'New Node', color: 'blue-grey', content: 'No content' }
  )

  // register the node style as the default for all new nodes
  const width = 300
  const height = 250

  graphComponent.graph.nodeDefaults.style = style
  graphComponent.graph.nodeDefaults.size = new Size(width, height)

  for (const { x, y, tag } of graphData) {
    graphComponent.graph.createNode({ layout: [x, y, width, height], style, tag })
  }
}

function App() {
  return (
    <div className="demo-main__graph-component">
      <DiagramComponent initGraph={initGraph} />
    </div>
  )
}

export default App

// demos/toolkit/angular/src/app/app.component.ts
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML 2.3.
 ** Copyright (c) 2000-2020 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import {
  AfterViewInit,
  ApplicationRef,
  Component,
  ComponentFactoryResolver,
  Injector,
  NgZone,
  ViewChild
} from '@angular/core'
import {
  IArrow,
  ICommand,
  IGraph,
  PolylineEdgeStyle,
  OrganicEdgeRouter,
  Size,
  TreeLayout,
  TreeReductionStage,
  INode
} from 'yfiles'
import { GraphComponentComponent } from './graph-component/graph-component.component'
import { EDGE_DATA, NODE_DATA } from './data'
import 'yfiles/view-layout-bridge.js'
import { Person } from './person'
import { NodeComponentStyle } from './NodeComponentStyle'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit {
  title = 'app'

  @ViewChild(GraphComponentComponent)
  private gcComponent!: GraphComponentComponent

  public currentPerson?: Person

  // eslint-disable-next-line no-useless-constructor
  constructor(
    private _injector: Injector,
    private _resolver: ComponentFactoryResolver,
    private _appRef: ApplicationRef,
    private _zone: NgZone
  ) {}

  ngAfterViewInit() {
    // run outside Angular so the change detection won't slow down yFiles
    this._zone.runOutsideAngular(() => {
      const graphComponent = this.gcComponent.graphComponent
      const graph = graphComponent.graph

      graph.nodeDefaults.size = new Size(285, 100)
      graph.nodeDefaults.style = new NodeComponentStyle(
        this._injector,
        this._resolver,
        this._appRef,
        this._zone
      )

      graph.edgeDefaults.style = new PolylineEdgeStyle({
        stroke: '2px rgb(170, 170, 170)',
        targetArrow: IArrow.NONE
      })

      graphComponent.addCurrentItemChangedListener(() => {
        this.currentPerson = graphComponent.currentItem!.tag
      })

      createSampleGraph(graph)

      runLayout(graph)

      graphComponent.fitGraphBounds()
    })
  }

  zoomIn() {
    this._zone.runOutsideAngular(() => {
      ICommand.INCREASE_ZOOM.execute(null, this.gcComponent.graphComponent)
    })
  }

  zoomOriginal() {
    this._zone.runOutsideAngular(() => {
      ICommand.ZOOM.execute(1, this.gcComponent.graphComponent)
    })
  }

  zoomOut() {
    this._zone.runOutsideAngular(() => {
      ICommand.DECREASE_ZOOM.execute(null, this.gcComponent.graphComponent)
    })
  }

  fitContent() {
    this._zone.runOutsideAngular(() => {
      ICommand.FIT_GRAPH_BOUNDS.execute(null, this.gcComponent.graphComponent)
    })
  }
}

function createSampleGraph(graph: IGraph): void {
  const nodeMap: { [name: string]: INode } = {}

  NODE_DATA.forEach(nodeData => {
    nodeMap[nodeData.name] = graph.createNode({
      tag: new Person(nodeData)
    })
  })

  EDGE_DATA.forEach(({ from, to }) => {
    const fromNode = nodeMap[from]
    const toNode = nodeMap[to]
    if (fromNode && toNode) {
      graph.createEdge(fromNode, toNode)
    }
  })
}

function runLayout(graph: IGraph): void {
  const treeLayout = new TreeLayout()
  const treeReductionStage = new TreeReductionStage()
  treeReductionStage.nonTreeEdgeRouter = new OrganicEdgeRouter()
  treeReductionStage.nonTreeEdgeSelectionKey = OrganicEdgeRouter.AFFECTED_EDGES_DP_KEY

  treeLayout.appendStage(treeReductionStage)

  graph.applyLayout(treeLayout)
}

<div class="demo-page__toolbar">
  <button
    (click)="zoomIn()"
    title="Zoom In"
    class="demo-icon-yIconZoomIn demo-toolbar-button"
  ></button>
  <button
    (click)="zoomOriginal()"
    title="Zoom to original size"
    class="demo-icon-yIconZoomOriginal demo-toolbar-button"
  ></button>
  <button
    (click)="zoomOut()"
    title="Zoom Out"
    class="demo-icon-yIconZoomOut demo-toolbar-button"
  ></button>
  <button
    (click)="fitContent()"
    title="Fit Content"
    class="demo-icon-yIconZoomFit demo-toolbar-button"
  ></button>
  <button
    (click)="exportSvg()"
    title="Export SVG"
    class="demo-icon-yIconSave demo-toolbar-button"
  ></button>
  <span class="demo-separator"></span>
  <input
    type="text"
    [ngModel]="searchString"
    (ngModelChange)="onSearchInput($event)"
    (keyup.enter)="graphSearch.zoomToSearchResult()"
    class="search"
    placeholder="Search Names"
    name="searchString"
  />
</div>

<div class="demo-page__main">
  <app-graph-overview-component class="demo-overlay"></app-graph-overview-component>
  <div class="demo-main__graph-component">
    <graph-component></graph-component>
  </div>
  <properties-view class="demo-main__sidebar" [person]="currentPerson"></properties-view>
</div>
